name = "dianping-agent"
compatibility_date = "2025-05-29"
main = "src/index.js"

[vars]
WEBHOOK_URL = ""
BACKUP_WEBHOOK_URL = ""
GOOGLE_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLSeMLNVU2xRD30LfyQlVW8UPEqOjlf9NLurD26G5t8axRP_TQw/formResponse"
# 你可以在这里添加自定义环境变量

[ai]
binding = "AI"  # 对应 env.AI
